"""add table product

Revision ID: 69dca0431dfc
Revises: 73571cb9fb09
Create Date: 2024-07-14 02:17:36.291250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69dca0431dfc'
down_revision: Union[str, None] = '73571cb9fb09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'product',
        sa.Column('uuid', sa.UUID, primary_key=True, autoincrement=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('description', sa.String, nullable=False),
        sa.Column('image', sa.Text, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('deleted_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='product_pkey'),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('product')  # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
