"""add table user

Revision ID: 73571cb9fb09
Revises:
Create Date: 2024-07-14 02:16:28.150807

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.helper.generator import generate_uuid, timezone

# revision identifiers, used by Alembic.
revision: str = '73571cb9fb09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user",
        sa.Column(name="uuid", type_=sa.UUID(), primary_key=True, default=generate_uuid()),
        sa.Column(name="email", type_=sa.String(length=255), unique=True, nullable=False),
        sa.Column(name="password", type_=sa.String(length=255), nullable=False),
        sa.Column(name="avatar", type_=sa.Text(), nullable=True),
        sa.Column(name="full_name", type_=sa.String(255), nullable=True),
        sa.Column(name="dob", type_=sa.Date(), nullable=True),
        sa.Column(name="is_member", type_=sa.Boolean(), default=False),
        sa.Column(name="is_staff", type_=sa.Boolean(), default=False),
        sa.Column(name="created_at", type_=sa.TIMESTAMP(timezone=True), default=datetime.now(tz=timezone)),
        sa.Column(name="updated_at", type_=sa.TIMESTAMP(timezone=True), onupdate=datetime.now(tz=timezone)),
        sa.Column(name="verification_at", type_=sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(name="deleted_at", type_=sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(name="created_by", type_=sa.String(length=255)),
        sa.Column(name="updated_by", type_=sa.String(length=255)),
        sa.Column(name="deleted_by", type_=sa.String(length=255)),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
